# Generated by Django 4.2.7 on 2025-06-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expensegroup_sharedexpense_expensegroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='default_split_type',
            field=models.CharField(choices=[('EQUAL', 'Split Equally'), ('PERCENTAGE', 'Split by Percentage'), ('CUSTOM', 'Custom Split')], default='EQUAL', max_length=10),
        ),
    ]
